import type { CSSProperties } from "react";
import {
  AppWindow,
  AppWindowMac,
  ArrowDown,
  ArrowLeftRight,
  ArrowRight,
  ArrowUp,
  Banknote,
  Battery,
  BatteryFull,
  BatteryLow,
  Bell,
  Bot,
  Brain,
  Bug,
  Building2,
  Calendar,
  Camera,
  CardSim,
  ChartLine,
  Check,
  CircleDollarSign,
  CircleDot,
  CircleHelp,
  CircuitBoard,
  Clock,
  Cloud,
  CloudUpload,
  Code,
  Computer,
  Cpu,
  CreditCard,
  Database,
  Download,
  Droplet,
  Drone,
  Eye,
  EyeOff,
  Factory,
  Fan,
  FileArchive,
  FileText,
  FingerprintPattern,
  Flag,
  Flame,
  Folder,
  Frown,
  Funnel,
  Gamepad2,
  Gauge,
  Glasses,
  Globe,
  Gpu,
  HardDrive,
  Headphones,
  Heart,
  Hourglass,
  House,
  Image,
  Info,
  KeyRound,
  Keyboard,
  Laptop,
  Leaf,
  Lightbulb,
  Link,
  ListChecks,
  Lock,
  LockOpen,
  Mail,
  Map,
  MapPin,
  MemoryStick,
  MessageSquare,
  Mic,
  Microchip,
  Minus,
  Monitor,
  Moon,
  Mouse,
  MousePointer2,
  Music,
  Network,
  Package,
  PcCase,
  Pencil,
  Percent,
  PersonStanding,
  Plane,
  Plug,
  Plus,
  Pointer,
  Presentation,
  Printer,
  Puzzle,
  QrCode,
  RadioTower,
  RectangleEllipsis,
  RefreshCw,
  Rocket,
  Router,
  Scale,
  ScanFace,
  Search,
  Server,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  ShoppingCart,
  Signal,
  Smartphone,
  SmartphoneNfc,
  Smile,
  Sparkles,
  Speaker,
  SquareTerminal,
  Star,
  Store,
  Sun,
  Tablet,
  Tag,
  Target,
  Thermometer,
  ThumbsUp,
  TrendingDown,
  TriangleAlert,
  Trophy,
  Truck,
  Tv,
  Upload,
  Usb,
  User,
  UserRound,
  Users,
  Video,
  Volume2,
  Wallet,
  Watch,
  Webcam,
  Wifi,
  Wrench,
  X,
  Zap,
  type LucideIcon,
} from "lucide-react";
import type { AidIcon } from "@planificador/core";

/**
 * La biblioteca de íconos de las M (la misma del panel anterior): íconos de
 * línea, en Crema o en Naranja marca cuando el elemento se resalta.
 */
export const ICONS: Record<AidIcon, LucideIcon> = {
  usuario: User,
  persona: PersonStanding,
  grupo: Users,
  persona_laptop: Presentation,
  cabeza: UserRound,
  cerebro: Brain,
  mano: Pointer,
  cara_feliz: Smile,
  cara_triste: Frown,
  rostro_escaneo: ScanFace,
  huella: FingerprintPattern,
  ojo: Eye,
  telefono: Smartphone,
  telefono_moderno: SmartphoneNfc,
  tablet: Tablet,
  laptop: Laptop,
  pantalla: Monitor,
  escritorio: Computer,
  mini_pc: PcCase,
  reloj_inteligente: Watch,
  audifonos: Headphones,
  teclado: Keyboard,
  mouse: Mouse,
  control_juego: Gamepad2,
  televisor: Tv,
  parlante: Speaker,
  camara: Camera,
  camara_web: Webcam,
  impresora: Printer,
  gafas_vr: Glasses,
  dron: Drone,
  router: Router,
  antena: RadioTower,
  microfono: Mic,
  volumen: Volume2,
  chip: Cpu,
  memoria: MemoryStick,
  ssd: Microchip,
  disco_duro: HardDrive,
  usb: Usb,
  enchufe: Plug,
  tarjeta_sd: CardSim,
  ventilador: Fan,
  tarjeta_grafica: Gpu,
  placa_base: CircuitBoard,
  bateria: Battery,
  bateria_baja: BatteryLow,
  bateria_llena: BatteryFull,
  rayo: Zap,
  termometro: Thermometer,
  wifi: Wifi,
  senal: Signal,
  servidor: Server,
  nube: Cloud,
  nube_subida: CloudUpload,
  ventana: AppWindow,
  navegador: AppWindowMac,
  terminal: SquareTerminal,
  codigo: Code,
  carpeta: Folder,
  documento: FileText,
  archivo_zip: FileArchive,
  descarga: Download,
  subida: Upload,
  campana: Bell,
  chat: MessageSquare,
  correo: Mail,
  calendario: Calendar,
  imagen: Image,
  video: Video,
  musica: Music,
  cursor: MousePointer2,
  toque: CircleDot,
  actualizar: RefreshCw,
  intercambio: ArrowLeftRight,
  enlace: Link,
  compartir: Share2,
  lista: ListChecks,
  lapiz: Pencil,
  ia: Sparkles,
  robot: Bot,
  base_datos: Database,
  red: Network,
  qr: QrCode,
  engranaje: Settings,
  lupa: Search,
  candado: Lock,
  candado_abierto: LockOpen,
  escudo: Shield,
  escudo_check: ShieldCheck,
  llave: KeyRound,
  contrasena: RectangleEllipsis,
  virus: Bug,
  ojo_tachado: EyeOff,
  alerta: TriangleAlert,
  dinero: Banknote,
  tarjeta: CreditCard,
  billetera: Wallet,
  moneda: CircleDollarSign,
  carrito: ShoppingCart,
  etiqueta_precio: Tag,
  porcentaje: Percent,
  grafica: ChartLine,
  tendencia_baja: TrendingDown,
  velocimetro: Gauge,
  trofeo: Trophy,
  balanza: Scale,
  embudo: Funnel,
  diana: Target,
  reloj: Clock,
  reloj_arena: Hourglass,
  casa: House,
  edificio: Building2,
  tienda: Store,
  fabrica: Factory,
  camion: Truck,
  paquete_envio: Package,
  avion: Plane,
  pin: MapPin,
  mapa: Map,
  mundo: Globe,
  bombilla: Lightbulb,
  cohete: Rocket,
  fuego: Flame,
  gota: Droplet,
  hoja: Leaf,
  sol: Sun,
  luna: Moon,
  rompecabezas: Puzzle,
  herramienta: Wrench,
  bandera: Flag,
  check: Check,
  equis: X,
  pregunta: CircleHelp,
  info: Info,
  mas: Plus,
  menos: Minus,
  flecha_sube: ArrowUp,
  flecha_baja: ArrowDown,
  flecha_derecha: ArrowRight,
  corazon: Heart,
  estrella: Star,
  pulgar: ThumbsUp,
};

/** Un ícono de la biblioteca, con el trazo fino del manual. */
export function AidIconView({
  name,
  size,
  color,
  style,
}: {
  name: AidIcon | null | undefined;
  size: number;
  color: string;
  style?: CSSProperties;
}) {
  if (!name) return null;
  const Icon = ICONS[name];
  return Icon ? (
    <Icon size={size} color={color} strokeWidth={1.5} absoluteStrokeWidth={false} style={style} />
  ) : null;
}
